<?php
// $Id$

/**
 * Implementation of hook_views_api().
 *
 * This one is used as the base to reduce errors when updating.
 */
function calendar_ical_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'calendar_ical'),
  );
}

/**
 * @file
 * Adds ical functionality to Calendar.
 */
function calendar_ical_theme() {
  return array(
    'calendar_ical_icon' => array(
      'arguments' => array('url'),
      ),
    'calendar_ical_feed' => array(
      'arguments' => array('view', 'items', 'type'),
      ),
    'calendar_ical_field' => array(
      'arguments' => array('fieldname', 'fields', 'field', 'node', 'view', 'type'),
      ),
    'calendar_ical_node' => array(
      'arguments' => array('node', 'view'),
      ),
    );
}

/**
 * Identify the cache where the ical feeds are stored.
 *
 * @return unknown
 */
function calendar_ical_cache() {
 return 'cache_views';
}

/**
 * Implementation of hook_cron().
 */
function calendar_ical_cron() {
 cache_clear_all('calendar_feeds_', calendar_ical_cache(), TRUE);
}

/**
 * Implementation of hook_calendar_add_items().
 */
function calendar_ical_calendar_add_items($view) {
  require_once('./'. drupal_get_path('module', 'date_api') .'/date_api_ical.inc');

  $items = array();
  $feeds = calendar_ical_add_feeds($view);
  foreach ($feeds as $feed) {
    if (!empty($feed->calendar_start) && !empty($feed->calendar_end)) {
      if ($feed->calendar_start >= date_format($view->date_info->min_date, DATE_FORMAT_DATETIME) && $feed->calendar_end <= date_format($view->date_info->max_date, DATE_FORMAT_DATETIME)) {
        // We have to add a calendar start and end object to the feed,
        // the cached date objects will not work correctly.
        $feed->calendar_start_date = date_make_date($feed->calendar_start, $feed->timezone);
        $feed->calendar_end_date = date_make_date($feed->calendar_end, $feed->timezone);
        $items[] = $feed;
      }
    }
  }
  return $items;
}

/**
 *  Implementation of hook_calendar_add_types().
 */
function calendar_ical_calendar_add_types($view) {
  return array('calendar_ical' => t('Calendar: iCal Feed'));
}

/**
 * Bring an ical feed into the calendar.
 *
 * @param $view - the view being manipulated
 * @param $refresh - whether or not to force a refresh of the feed
 * @return $nodes to add to calendar
 * @todo probably need to add more validation of the results in case the url doesn't work.
 */

function calendar_ical_add_feeds($view, $refresh = FALSE) {
  $nodes = array();
  $feeds = variable_get('calendar_feeds_'. $view->name, array());
  $expire = intval(variable_get('calendar_ical_expire_'. $view->name, 9676800) + time());
  foreach ($feeds as $delta => $feed) {
    if ($view->build_type == 'page') {
      $GLOBALS['calendar_stripe_labels'][$feed['stripe']] = $feed['name'];
    }
    if (!$refresh && $cached = cache_get('calendar_feeds_'. $view->name .':'. $feed['url'], calendar_ical_cache())) {
      $nodes += (array) $cached->data;
    }
    else {
      $expire = intval(variable_get('calendar_ical_expire_'. $view->name, 9676800) + time());
      require_once('./'. drupal_get_path('module', 'date_api') .'/date_api_ical.inc');

      switch ($feed['type']) {
      case 'ical':
        $filename = $feed['url'];
        $default = $feed['link'];
        $new_nodes = array();
        $calendars = date_ical_import($filename);
        foreach ($calendars as $calendar) {
          if (empty($calendars)) {
            continue;
          }
          foreach ($calendars as $calendar) {
            if (empty($calendar) || empty($calendar['VEVENT'])) {
              continue;
            }
            if (empty($value['DTSTART'])) continue;
            $node = new stdClass();
            $node->nid = $value['UID'];
            $node->title = $value['SUMMARY'];
            $node->label = $feed['name'];
            $node->teaser =  $value['DESCRIPTION'];
            $node->timezone = $value['DTSTART']['tz'];
            $node->calendar_start_date = date_ical_date($value['DTSTART'], $value['DTSTART']['tz']);
            $node->calendar_start = date_format_date($node->calendar_start_date, 'custom', DATE_FORMAT_DATETIME);
            $node->calendar_end_date = date_ical_date($value['DTEND'], $value['DTEND']['tz']);
            $node->calendar_end = date_format_date($node->calendar_end_date, 'custom', DATE_FORMAT_DATETIME);
            $show_tz = ' e';
            $granularity = $value['DTSTART']['type'] == 'DATE' ? array('year', 'month', 'day') : array('year', 'month', 'day', 'hour', 'minute', 'second');
            $node->format_time = variable_get('calendar_time_format_'. $view->name, 'H:i');
            $node->format = date_limit_format(variable_get('date_format_short', 'm/d/Y - H:i'), $granularity) . $show_tz;
            $node->all_day = $value['DTSTART']['all_day'];
            $node->stripe = $feed['stripe'];
            $node->stripe_label = $feed['name'];
            $node->remote = TRUE;
            $node->uid = $value['uid'] ? $value['UID'] : calendar_get_node_link($node, $default);
            $node->url = $value['URL'] ? $value['URL'] : calendar_get_node_link($node, $default);
            $node->calendar_node_theme = 'calendar_ical_node';
            $node->calendar_field_theme = 'calendar_ical_field';
            $new_nodes[$value['UID']] = $node;
          }
          if (!empty($new_nodes)) {
            cache_set('calendar_feeds_'. $view->name .':'. $feed['url'], $new_nodes, calendar_ical_cache(), $expire);
            $nodes += (array) $new_nodes;
          }
          break;
        }
      }
    }
  }
  return $nodes;
}

/**
 * feed argument hook that will convert us to ical or display an icon.
 * the 4th argument isn't part of the hook, but we use it to differentiate
 * when called as a hook or when called manually from calendar_ical_views_post_view
 */
function calendar_ical_views_feed_argument($op, &$view, $arg, $argtype = NULL) {
 if ($op == 'argument' && $arg == 'ical') {
    // Keep devel module from appending queries to ical export.
   $GLOBALS['devel_shutdown'] = FALSE;
    $view->page_type = 'calendar_ical';
    // reset the 'real url' to the URL without the feed argument.
    $view_args = array();
    $max = count($view->args);
    foreach ($view->args as $id => $view_arg) {
      ++$count;
      if ($view_arg == $arg && $view->argument[$id]['id'] == $argtype['id']) {
        if ($count != $max) {
          $view_args[] = $argtype['wildcard'];
        }
      }
      else {
        $view_args[] = $view_arg;
      }
    }
    $view->feed_url = views_get_url($view, $view_args);
  }
  else if ($op == 'post_view') {
    $args = calendar_ical_post_view_make_args($view, $arg, 'ical');
    $url = views_get_url($view, $args);
    $title = views_get_title($view, 'page', $args);
    if ($view->used_filters) {
      $filters = drupal_query_string_encode($view->used_filters);
    }
    return implode(calendar_ical_add_ical(url($url, $filters), $title));
  }
}

function calendar_ical_add_feed($url = NULL, $title = '') {
  if (!is_null($url)) {
    $stored_feed_links[$url] = theme('calendar_ical_icon', $url);
    drupal_add_link(array('rel' => 'alternate',
                          'type' => 'application/calendar',
                          'title' => $title,
                          'href' => $url));
  }
  return $stored_feed_links;
}

function theme_calendar_ical_icon($url) {
  if ($image = theme('image', drupal_get_path('module', 'date_api') .'/images/ical16x16.gif', t('Add to calendar'), t('Add to calendar'))) {
    return '<div style="text-align:right"><a href="'. check_url($url) .'" class="ical-icon" title="ical">'. $image .'</a></div>';
  }
}

/**
 * Theme for an entire ical node.
 */
function theme_calendar_ical_node($node, $view) {
  // Check plain may leave html entities in the title.
  $node->title = html_entity_decode(check_plain($node->title), ENT-QUOTES);
  $node->teaser = check_markup($node->teaser);

  if ($view->date_info->calendar_display == 'calendar') {
    // Remote nodes may come in with lengthy descriptions that won't fit
    // in small boxes of year, month, and week calendars.
    if ($view->date_info->date_type != 'day') {
      $node->teaser = '';
    }
    $theme = 'calendar_node_'. $view->date_info->date_type;
    return theme($theme, $node, $view);
  }
  else {
    // Create a pseudo node view for this item.
    $output  = '<div class="node">';
    $output .= '<h2>'. l($node->title, $node->url) .'</h2>';
    $output .= '<div>'. theme('calendar_date_combo', $node, $node->format, t('Dates'), $view)  .'</div>';
    $output .= '<div class="content">'. $node->teaser .'</div>';
    $output .= '</div>';
    return $output;
  }
}

/**
 * Views field theme for an ical field.
 *
 * Used for table and list views.
 *
 * For non-calendar views that use fields, the field needs a value from the
 * imported node that matches the kind of field in the view. Most possible
 * Views fields make no sense here and will return nothing.
 */
function theme_calendar_ical_field($fieldname, $fields, $field, $node, $view, $type) {
  static $datefield;

  // Find the first date field in the view to attach the ical date to.
  // There may be more than one date field in the view and we only
  // want to put the ical field in one place.
  if (empty($datefield)) {
    $calendar_fields = date_api_fields();
    foreach ($view->field as $viewfield) {
      if (in_array($viewfield['field'], array_keys($calendar_fields))) {
        $datefield = $viewfield['queryname'];
        break;
      }
    }
  }

  // Check plain may leave html entities in the title.
  $node->title = html_entity_decode(check_plain($node->title), ENT-QUOTES);
  $node->teaser = check_markup($node->teaser);

  // Fix some common html entities that may not get decoded correctly.
  // You can add more of them in this array.
  $replace = array(
    '&#039;' => "'",
    );
  foreach (array('title', 'teaser') as $key) {
    $node->$key = strtr($node->$key, $replace);
  }

  if ($fieldname == $datefield) {
    return theme('calendar_date_combo', $node, '', $view);
  }

  switch ($field['fullname']) {
    case 'node.title':
      return l($node->title, $node->url);

    case 'node.teaser':
    case 'node.body':
      return $node->teaser;

    case 'node.type':
      return $node->label;
  }
  return;

}